// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kPYlOZrkEMRlTpbqZplOvrvVupF1NEg',
    appId: '1:214537528312:web:836a443d1ca00d1e2c2c0d',
    messagingSenderId: '214537528312',
    projectId: 'safe-qr-app',
    authDomain: 'safe-qr-app.firebaseapp.com',
    storageBucket: 'safe-qr-app.firebasestorage.app',
    measurementId: 'G-E4TT665KQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqQttNtpVdqnCMdKlLst6mWHPsxi0Bug',
    appId: '1:214537528312:android:d675e16d93bbafcd2c2c0d',
    messagingSenderId: '214537528312',
    projectId: 'safe-qr-app',
    storageBucket: 'safe-qr-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7vjvjY-LAuiuylq8mSzesJzHriwFXKBQ',
    appId: '1:214537528312:ios:b136c4c023d5d8742c2c0d',
    messagingSenderId: '214537528312',
    projectId: 'safe-qr-app',
    storageBucket: 'safe-qr-app.firebasestorage.app',
    iosBundleId: 'com.example.safeQrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7vjvjY-LAuiuylq8mSzesJzHriwFXKBQ',
    appId: '1:214537528312:ios:b136c4c023d5d8742c2c0d',
    messagingSenderId: '214537528312',
    projectId: 'safe-qr-app',
    storageBucket: 'safe-qr-app.firebasestorage.app',
    iosBundleId: 'com.example.safeQrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kPYlOZrkEMRlTpbqZplOvrvVupF1NEg',
    appId: '1:214537528312:web:2bb2e9242dae9a8e2c2c0d',
    messagingSenderId: '214537528312',
    projectId: 'safe-qr-app',
    authDomain: 'safe-qr-app.firebaseapp.com',
    storageBucket: 'safe-qr-app.firebasestorage.app',
    measurementId: 'G-NF15EHWNG5',
  );
}
